name: publish to nuget
on:
 push:
    tags:
      - 'v*'
jobs:
  publish:
    name: build, pack & publish
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: get version
        run: echo "RELEASE_VERSION=$(echo ${{github.ref_name}} | sed -e "s/v//gI")" >> $GITHUB_ENV

      - name: Setup dotnet
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 3.1.x

      # Publish
      - name: publish on version change
        id: publish_nuget
        uses: rohith/publish-nuget@v2
        with:
          PROJECT_FILE_PATH: akeyless-dotnet-cloudid.csproj
          PACKAGE_NAME: akeyless.Cloudid
          VERSION_STATIC: ${{env.RELEASE_VERSION}}

          # Flag to toggle git tagging, enabled by default
          TAG_COMMIT: false

          # API key to authenticate with NuGet server
          NUGET_KEY: ${{secrets.NUGET_API_KEY}}